name: CI/CD Pipeline

on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Run tests
      run: |
        python -m unittest discover -s person1 -p "*.py"
    - name: Generate documentation
      run: |
        mkdir docs
        echo "# API Documentation" > docs/README.md
        echo "## Functions" >> docs/README.md
        echo "- add(a, b): returns a + b" >> docs/README.md
        echo "- multiply(a, b): returns a * b" >> docs/README.md
        echo "" >> docs/README.md
        echo "## Tests" >> docs/README.md
        echo "- test_add: проверяет сложение" >> docs/README.md
        echo "- test_multiply: проверяет умножение" >> docs/README.md
        echo "" >> docs/README.md
        echo "## CI/CD" >> docs/README.md
        echo "Проект использует GitHub Actions для автоматического тестирования и генерации документации." >> docs/README.md
    
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/
