name: CI/CD Pipeline

on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Run tests
      run: |
        python -m unittest discover -s person1 -p "*.py"
    - name: Generate documentation
      run: |
        mkdir docs
        python -m pydoc -w person1.utils > docs/utils.html
        python -m pydoc -w person1.test_utils > docs/test_utils.html
    
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/
